http:
  listner:
    host: "localhost"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  oracle:
    host: "localhost"
    port: "1521"
    username: "dummy"
    password: "dummy"
    service: "XE"
