http:
  listner:
    host: "0.0.0.0"
    port: "9082"
    path: "/fastGoCall/{serviceType}"
    
db:
  oracle:
    host: "localhost"
    port: "1521"
    username: "dummy"
    password: "dummy"
    service: "XE"
